# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['sounddevice', 'numpy', 'keyboard', '_sounddevice_data'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch', 'torchvision', 'torchaudio',
        'tensorflow', 'tensorboard',
        'django',
        'scipy', 'sklearn',
        'pandas',
        'matplotlib',
        'PIL', 'Pillow',
        'cv2',
        'transformers',
        'onnxruntime',
        'boto3', 'botocore',
        'sqlalchemy',
        'pytest', 'py',
        'IPython', 'jupyter', 'notebook',
        'pygments',
        'lxml',
        'pyarrow',
        'numba', 'llvmlite',
        'librosa', 'soundfile',
        'yt_dlp',
        'Crypto', 'cryptography', 'bcrypt',
        'grpc', 'grpcio',
        'psycopg2',
        'uvicorn', 'starlette', 'fastapi',
        'imageio', 'imageio_ffmpeg',
        'altair', 'jsonschema', 'jsonschema_specifications',
        'jinja2', 'mako',
        'openpyxl',
        'fsspec',
        'av',
        'regex',
        'tkinter', '_tkinter',
        'narwhals',
        'opentelemetry',
        'websockets',
        'dns',
        'win32com',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='EchoType',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)
